### ISSUE TITLE
Passing in a component instead of a tag

### ISSUE THREAD

**Issue by lukejacksonn** [picostyle/picostyle#17]
```js
// styles.js

import { h } from 'hyperapp'
import style from 'picostyle'
const ps = style(h)

export const Nav = ps('nav')({
  position: 'fixed',
})

const Link = ({ url, text }) =>
  <a href={url}>{text}</a>

export const StyledLink = ps(Link)({
  background: 'red'
})
```
```js
// index.js

import { h, app } from 'hyperapp'
import { Nav, StyledLink } from './styles'

app({
  state: {},
  view: () => <Nav><StyledLink url='/' text='Home' /></Nav>
})
```

When I run the code above this is rendered:

```
<nav class='p0'>
  <a href='/'>Home</a>
</nav>
```

Elements created with a tag name as a string (like `ps('nav')`) get a style class added.. but any element created with tag as a component (like `ps(Link)`) does not get the class added to it.

Not sure if this is intentional or even possible to achieve.. but I know `h` accepts a string or a component as a the first argument.. and looking at the code [here](https://github.com/picostyle/picostyle/blob/master/src/index.js#L48) it looks as though that is all that we are doing with `tag`.

Any hints as to my wrong doing would be very much appreciated!

**Comment by morishitter** [comment]
@lukejacksonn Just released v0.1.4 fixed this bug. Thank you for your report :)
